name: Keep Render App Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to keep Render alive
        run: curl -s -o /dev/null https://https://gmtvehicles-089y.onrender.com/
